apiVersion: v1
baseDomain: gpfs.net
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: scale
networking:
  clusterNetworks:
  - cidr: 10.254.0.0/16
    hostPrefix: 24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 10.0.100.0/24
platform:
  none: {}
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZWViNGFhNjUzMWQ2NGVkODk4ZmZjMWEyM2UxNzAwNjE6NUM2MVVCVzZVMkUxUUI5WlRaTkZBRzlXUUpDTUc1UThNV1lZNkxMSUMxT0xDSTFMTDlYQ09DUlI3RzJURlVMRQ==","email":"lixuesh@cn.ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZWViNGFhNjUzMWQ2NGVkODk4ZmZjMWEyM2UxNzAwNjE6NUM2MVVCVzZVMkUxUUI5WlRaTkZBRzlXUUpDTUc1UThNV1lZNkxMSUMxT0xDSTFMTDlYQ09DUlI3RzJURlVMRQ==","email":"lixuesh@cn.ibm.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWQ5MTlhYWVmLTMwY2UtNDE0Ny05NGY3LTU4ODllZDYyNjFkZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpPVE5rTmprMU5HSXlZMlkwWlRFMFlqZGhaakprTkRBNU5EWmxORFpoTlNKOS5OTFQyeUVWNVVGZFNfQmVfRG81TjVHOFYwSnZsbUtVU0REbTk3VjdWVm0xMkhLeG1fcjFfM0ExaXJaYnh2MEJTMXg1TDd5eWM4X2ljZ2YxbVlUX1pDbm9YYWRqWWJXa3FiMGFKWWM1LTVUTk9iM1JPVFRralA0YXJzeW1PcWhFS25EZDZKYWJtWW13WFJ2cDNOT0VBNWR5cS1LTjNuV1c5ZmtKZk1lUDR4Sk1ZdThwcm1wd2RXVHd6OTFaS3NYTVpteDZYMTNkcTRLVXFXZEhyTVU1NFA2QlQ5cDFJMUdlZ1FzbGNDYUFPQ3VfUklEbjVmN2pQZlVHYUk1TGhscWpRRDNuX1Jza1ZLMnJzblFPdllVZnZnNG90QzdFdlVVNS16WTM0UUZheVNYUThTMTJ4bDd5aFdUN0lXNmNVbkI4dmxVWjluNHphM0w3aGJ1SnNBTGhYcWlPQ3BoOWFSNVRONW9RMl83aG51Snh6QWw2LUNHcEFCYmFBMjQ4Sl9mdkljRkNnb19RTWliaHFBcTcyNlZvdzIyRXZjTnQ4NkU0WnpselkwVzZMVWR3VklzdzU3a0NFUjlGYUpIRGltdFE0UnhHVW9icEE1QVZYZGh4Q0pHZUpHT2Z6aHFaSUpqRENoM1ZMLWloTjJGS3dPRlNCTi13a2VMbjk5NWpnVjd6TGluaEZqMzV5SlR2bEt1eEZtVzRCeE5jY0Y2eTlsb0tGT2hCX1ZkcFpIUDVPel8yeUZxTmpxNU5sUldVcnpOUDVva2QyLXM5UGFrUURoNmFNcFhIZ2QwN3c3LVZNcGhLb3hnVE1ZeFlnb1BfT3FGQjBYSEtpVHprcFlZMkJuSUdRUjJFZ2FjT2xmbXdibTFTeUN4VDdXS2s5YW9YRzJuQ1diTWpzUU1wRm1zdw==","email":"lixuesh@cn.ibm.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWQ5MTlhYWVmLTMwY2UtNDE0Ny05NGY3LTU4ODllZDYyNjFkZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpPVE5rTmprMU5HSXlZMlkwWlRFMFlqZGhaakprTkRBNU5EWmxORFpoTlNKOS5OTFQyeUVWNVVGZFNfQmVfRG81TjVHOFYwSnZsbUtVU0REbTk3VjdWVm0xMkhLeG1fcjFfM0ExaXJaYnh2MEJTMXg1TDd5eWM4X2ljZ2YxbVlUX1pDbm9YYWRqWWJXa3FiMGFKWWM1LTVUTk9iM1JPVFRralA0YXJzeW1PcWhFS25EZDZKYWJtWW13WFJ2cDNOT0VBNWR5cS1LTjNuV1c5ZmtKZk1lUDR4Sk1ZdThwcm1wd2RXVHd6OTFaS3NYTVpteDZYMTNkcTRLVXFXZEhyTVU1NFA2QlQ5cDFJMUdlZ1FzbGNDYUFPQ3VfUklEbjVmN2pQZlVHYUk1TGhscWpRRDNuX1Jza1ZLMnJzblFPdllVZnZnNG90QzdFdlVVNS16WTM0UUZheVNYUThTMTJ4bDd5aFdUN0lXNmNVbkI4dmxVWjluNHphM0w3aGJ1SnNBTGhYcWlPQ3BoOWFSNVRONW9RMl83aG51Snh6QWw2LUNHcEFCYmFBMjQ4Sl9mdkljRkNnb19RTWliaHFBcTcyNlZvdzIyRXZjTnQ4NkU0WnpselkwVzZMVWR3VklzdzU3a0NFUjlGYUpIRGltdFE0UnhHVW9icEE1QVZYZGh4Q0pHZUpHT2Z6aHFaSUpqRENoM1ZMLWloTjJGS3dPRlNCTi13a2VMbjk5NWpnVjd6TGluaEZqMzV5SlR2bEt1eEZtVzRCeE5jY0Y2eTlsb0tGT2hCX1ZkcFpIUDVPel8yeUZxTmpxNU5sUldVcnpOUDVva2QyLXM5UGFrUURoNmFNcFhIZ2QwN3c3LVZNcGhLb3hnVE1ZeFlnb1BfT3FGQjBYSEtpVHprcFlZMkJuSUdRUjJFZ2FjT2xmbXdibTFTeUN4VDdXS2s5YW9YRzJuQ1diTWpzUU1wRm1zdw==","email":"lixuesh@cn.ibm.com"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClX+Y7lHB3LME2IVg0ZqXZW7+FR7crmz8MbdS7+aZc07Kz/ZNZbDt3ghjuTl/vuoxogEAsH1zuD2Ou20d0T1si6CWXR6RY1U289lOGSYOTkAwCkM5rplTvsxPZZT/WG0NTjU7qowQD6wIEaauMcwRT1WqeYN60/QmaB14xccreTOQzYcbgltwmBX68D2n6JnXwo30YySBkMF5Y4/hx0plKH6Q6pFvodX6S37VX/mw723EVbSAbCEZC/tz3tPcad+aVH5DPGG5V5YWFQ+7mQTsTUBO2YvJcHv3t9nK2Oj+ZrhC1iCtQhTGRYROWMqVFgrYEDDh9XWr5lZLx1pTLve35'
#additionalTrustBundle: |
#  -----BEGIN CERTIFICATE-----
#  ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
#  -----END CERTIFICATE-----
#imageContentSources:
#- mirrors:
#  - registry.ocp4.example.com:5000/ocp4/openshift4
#  source: quay.io/openshift-release-dev/ocp-release-nightly
#- mirrors:
#  - registry.ocp4.example.com:5000/ocp4/openshift4
#  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
